name: Tidy and Test

runs:
  using: composite
  steps:
    # TODO: FIX ME

    # - name: Ensure everything is tidy
    #   shell: bash
    #   run: |
    #     bazelisk run //:tidy_check

    # - name: Execute Bazel Tests
    #   shell: bash
    #   run: |
    #     bazelisk test //... 

    # - name: Execute Swift Tests
    #   shell: bash
    #   run: |
    #     swift test

    - name: DEBUG
      shell: bash
      run: |
        echo >&2 "BUILD Truth Tests"
        bazelisk build //Tests/TruthTests/...
        echo >&2 "Test Truth Tests"
        bazelisk test //Tests/TruthTests/...
