name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: swift_toolbox

    - name: Execute Tests
      shell: bash
      run: |
        bazelisk test //... 

    - name: Build Anything Not Tested
      shell: bash
      run: |
        bazelisk build //... 
