name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 11:17 UTC.
    - cron: '17 11 * * *'

jobs:
  macos_build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "15.0"
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: swift_toolbox
    - uses: ./.github/actions/tidy_and_test

  ubuntu_build:
    runs-on: ubuntu-22.04
    env:
      CC: clang
    steps:
    - uses: cgrindel/gha_install_swift_on_ubuntu@v1
      with:
        swift_release_tag: "swift-5.8.1-RELEASE"
        ubuntu_version: "22.04"
    - uses: actions/checkout@v3
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: swift_toolbox
    - name: Update local.bazelrc with Linux Flags
      shell: bash
      run: |
        cat >> "local.bazelrc" <<EOF
        # Need to expose the PATH so that the Swift toolchain can be found
        build --action_env=PATH
        EOF
    - uses: ./.github/actions/tidy_and_test

  all_ci_tests:
    runs-on: ubuntu-latest
    needs:
      - macos_build
      - ubuntu_build
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

